#!/usr/bin/env bash

source commands/settings.txt

DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE} \
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY} \
DATABASE_ENGINE=${DATABASE_ENGINE} \
DATABASE_NAME=${DATABASE_NAME} \
DATABASE_USER=${DATABASE_USER} \
DATABASE_PASSWORD=${DATABASE_PASSWORD} \
DATABASE_HOST=${DATABASE_HOST} \
DATABASE_PORT=${DATABASE_PORT} \
PIP_REQUIREMENTS=${PIP_REQUIREMENTS} \
docker-compose up --build --detach